let x = 150; 
let a = Math.PI;
let b = +a.toFixed(2);
let c = Math.max(15, 11, 16, 12,51, 12, 13, 51);
let d = Math.min(15, 11, 16, 12,51, 12, 13, 51);
let e = Math.random() * x;
let f = +e.toFixed(2);
let h = 0.6 + 0.7;
let g = +h.toFixed(2);
let y = parseInt('100$');
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(h);
console.log(g);
console.log(y);
let str = 'some test string';
value = str[0];
value1 = str[str.length - 1];
console.log(value, value1);
value2 = value.toUpperCase();
value3 = value1.toUpperCase();
console.log(value2 , value3); 
value4 = str.indexOf('string');
console.log(value4);
value5 = str.lastIndexOf(' ');
console.log(value5);
value6 = str.slice(5 , 9);
console.log(value6);
value7 = str.slice(-6);
console.log(value7);
let z = 20;
let o = 23;
